salesforce:
  username: "priadhikari.d7df45ca9572@agentforce.com"
  clientId: "${salesforce.clientId}"
  clientSecret: "${salesforce.clientSecret}"

jms:
  brokerUrl: "tcp://localhost:61616"
  queueName: "CONTACT.ONBOARDING.Q"
  dlqName: "CONTACT.ONBOARDING.DLQ"

retry:
  maxRetries: "3"
  retryInterval: "5000"